# coding=utf-8

from __future__ import absolute_import

from talos.db import crud
from talos.db import converter
from wecubek8s.db import validator

cluster_rules = [
    crud.ColumnValidator(field='name', rule=validator.LengthValidator(1, 255), validate_on=['check:M'], nullable=False),
    crud.ColumnValidator(field='correlation_id',
                         rule=validator.LengthValidator(1, 64),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='api_server',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='token',
                         rule=validator.LengthValidator(1, 2048),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='image_pull_username',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='image_pull_password',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='private_registry',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
]

cluster_destroy_rules = [
    crud.ColumnValidator(field='name', rule=validator.LengthValidator(1, 255), validate_on=['check:M'], nullable=False),
]

tag_item_rules = [
    crud.ColumnValidator(field='name', rule=validator.LengthValidator(1, 255), validate_on=['check:M'], nullable=False),
    crud.ColumnValidator(field='value', rule=validator.TypeValidator(str), validate_on=['check:M'], nullable=False),
]

image_item_rules = [
    crud.ColumnValidator(field='name', rule=validator.LengthValidator(1, 255), validate_on=['check:M'], nullable=False),
    crud.ColumnValidator(field='ports', rule=validator.LengthValidator(0, 512), validate_on=['check:O'], nullable=True),
]

# env = name, value, valueFrom
#   valueFrom in [configMapKeyRef, fieldRef, resourceFieldRef, secretKeyRef]
#     * configMapKeyRef = name,key
#     * secretKeyRef = name,key
#     * fieldRef = fieldPath
#     [unsupported]resourceFieldRef = containerName, resource, divisor
env_item_rules = [
    crud.ColumnValidator(field='name', rule=validator.LengthValidator(1, 255), validate_on=['check:M'], nullable=False),
    crud.ColumnValidator(field='value', rule=validator.TypeValidator(str), validate_on=['check:M'], nullable=False),
    crud.ColumnValidator(field='valueFrom',
                         rule=validator.InValidator(['value', 'configMap', 'secretKey', 'fieldRef']),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='valueRef',
                         rule=validator.MappingValidator(crud.ColumnValidator.get_clean_data, tag_item_rules, 'check'),
                         validate_on=['check:O'],
                         converter=validator.StringToDict(),
                         nullable=True),
]

# volume = name, mountPath, readOnly, type,
#   type in [configMap, hostPath, emptyDir, secret, nfs]
#           [cephfs, cinder, csi, fc, glusterfs, iscsi, persistentVolumeClaim, rbd, vsphereVolume]
#           see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#volume-v1-core for more
volume_item_rules = [
    crud.ColumnValidator(field='name', rule=validator.LengthValidator(1, 255), validate_on=['check:M'], nullable=False),
    crud.ColumnValidator(field='mountPath',
                         rule=validator.LengthValidator(1, 1024),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='readOnly',
                         validate_on=['check:O'],
                         nullable=False,
                         converter=converter.BooleanConverter()),
    crud.ColumnValidator(field='type',
                         rule=validator.InValidator(
                             ['configMap', 'hostPath', 'emptyDir', 'secret', 'nfs', 'persistentVolumeClaim']),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='typeSpec', rule=validator.TypeValidator(dict), validate_on=['check:O'], nullable=True),
]

deployment_rules = [
    crud.ColumnValidator(field='cluster',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='correlation_id',
                         rule=validator.LengthValidator(1, 64),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='name', rule=validator.LengthValidator(1, 255), validate_on=['check:M'], nullable=False),
    # default 'default'
    crud.ColumnValidator(field='namespace',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
    # 改为单个镜像的两个字段
    crud.ColumnValidator(field='image_name',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='image_port',
                         rule=validator.LengthValidator(0, 512),
                         validate_on=['check:O'],
                         nullable=True),
    # default no auth
    crud.ColumnValidator(field='image_pull_username',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='image_pull_password',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
    # tag: {name: xxx, value: xxxx}
    crud.ColumnValidator(field='tags',
                         rule=validator.IterableValidator(crud.ColumnValidator.get_clean_data, tag_item_rules, 'check'),
                         validate_on=['check:O'],
                         converter=validator.StringToList(),
                         nullable=True),
    crud.ColumnValidator(field='replicas',
                         rule=validator.RegexValidator(r'^\d+$'),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='cpu',
                         rule=validator.RegexValidator(r'^(((\d+\.\d+)|(\d+))m?)?$'),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='memory',
                         rule=validator.RegexValidator(r'^((\d+)(Ei|Pi|Ti|Gi|Mi|Ki|E|P|T|G|M|K)?)?$'),
                         validate_on=['check:O'],
                         nullable=True),
    # for stateful set, difference env & volume for each pod
    crud.ColumnValidator(field='pod_tags',
                         rule=validator.IterableValidator(crud.ColumnValidator.get_clean_data, tag_item_rules, 'check'),
                         validate_on=['check:O'],
                         converter=validator.StringToList(),
                         nullable=True),
    crud.ColumnValidator(field='affinity',
                         rule=validator.InValidator(['anti-host-preferred', 'anti-host-required']),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='envs',
                         rule=validator.IterableValidator(crud.ColumnValidator.get_clean_data, env_item_rules, 'check'),
                         validate_on=['check:O'],
                         converter=validator.StringToList(),
                         nullable=True),
    crud.ColumnValidator(field='volumes',
                         rule=validator.IterableValidator(crud.ColumnValidator.get_clean_data, volume_item_rules,
                                                          'check'),
                         validate_on=['check:O'],
                         converter=validator.StringToList(),
                         nullable=True),
    crud.ColumnValidator(field='packageUrl',
                         rule=validator.LengthValidator(0, 2048),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='instanceId',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='deployment_path',
                         rule=validator.LengthValidator(0, 1024),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='process_name',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='process_keyword',
                         rule=validator.LengthValidator(0, 512),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='image_deploy_script',
                         rule=validator.LengthValidator(0, 8192),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='log_path',
                         rule=validator.RegexValidator(r'^(/[a-zA-Z0-9_\-./]*)?$'),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='block_storage',
                         rule=validator.TypeValidator(list),
                         validate_on=['check:O'],
                         nullable=True),
    # 共享 PVC 的 GUID 数组，引用已存在的共享 PVC（多 Pod 共用同一 PVC）
    crud.ColumnValidator(field='shared_block_storage',
                         rule=validator.TypeValidator(list),
                         validate_on=['check:O'],
                         nullable=True),
    # StatefulSet metadata 注解，格式同 tags（{name, value} 数组），合并写入 annotations
    crud.ColumnValidator(field='annotations',
                         rule=validator.IterableValidator(crud.ColumnValidator.get_clean_data, tag_item_rules, 'check'),
                         validate_on=['check:O'],
                         converter=validator.StringToList(),
                         nullable=True),
    crud.ColumnValidator(field='volumeClaimTemplates',
                         rule=validator.TypeValidator(list),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='volumeClaimMounts',
                         rule=validator.TypeValidator(list),
                         validate_on=['check:O'],
                         nullable=True),
    # 共享 PVC 的 Pod-level volumes 配置（由 parse_and_build_shared_pvc_volumes 生成）
    crud.ColumnValidator(field='sharedPvcVolumes',
                         rule=validator.TypeValidator(list),
                         validate_on=['check:O'],
                         nullable=True),
    # 共享 PVC 的容器挂载配置（由 parse_and_build_shared_pvc_volumes 生成）
    crud.ColumnValidator(field='sharedPvcMounts',
                         rule=validator.TypeValidator(list),
                         validate_on=['check:O'],
                         nullable=True),
]

# DaemonSet 规则（类似 deployment_rules，但不需要 replicas 和 affinity）
daemonset_rules = [
    crud.ColumnValidator(field='cluster',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='correlation_id',
                         rule=validator.LengthValidator(1, 64),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='name', rule=validator.LengthValidator(1, 255), validate_on=['check:M'], nullable=False),
    crud.ColumnValidator(field='namespace',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='image_name',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='image_port',
                         rule=validator.LengthValidator(0, 512),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='tags',
                         rule=validator.IterableValidator(crud.ColumnValidator.get_clean_data, tag_item_rules, 'check'),
                         validate_on=['check:O'],
                         converter=validator.StringToList(),
                         nullable=True),
    crud.ColumnValidator(field='pod_tags',
                         rule=validator.IterableValidator(crud.ColumnValidator.get_clean_data, tag_item_rules, 'check'),
                         validate_on=['check:O'],
                         converter=validator.StringToList(),
                         nullable=True),
    crud.ColumnValidator(field='cpu',
                         rule=validator.RegexValidator(r'^(((\d+\.\d+)|(\d+))m?)?$'),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='memory',
                         rule=validator.RegexValidator(r'^((\d+)(Ei|Pi|Ti|Gi|Mi|Ki|E|P|T|G|M|K)?)?$'),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='envs',
                         rule=validator.IterableValidator(crud.ColumnValidator.get_clean_data, env_item_rules, 'check'),
                         validate_on=['check:O'],
                         converter=validator.StringToList(),
                         nullable=True),
    crud.ColumnValidator(field='volumes',
                         rule=validator.IterableValidator(crud.ColumnValidator.get_clean_data, volume_item_rules,
                                                          'check'),
                         validate_on=['check:O'],
                         converter=validator.StringToList(),
                         nullable=True),
    crud.ColumnValidator(field='node_selector',
                         rule=validator.TypeValidator(dict),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='tolerations',
                         rule=validator.TypeValidator(list),
                         validate_on=['check:O'],
                         nullable=True),
]

service_rules = [
    crud.ColumnValidator(field='cluster',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='correlation_id',
                         rule=validator.LengthValidator(1, 64),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='name', rule=validator.LengthValidator(1, 255), validate_on=['check:M'], nullable=False),
    # default 'default'
    crud.ColumnValidator(field='namespace',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
    # default ClusterIP, other choices: NodePort/ClusterIP/LoadBalancer
    crud.ColumnValidator(field='type',
                         rule=validator.InValidator(['NodePort', 'ClusterIP', 'LoadBalancer']),
                         validate_on=['check:O'],
                         nullable=True),
    # when type=ClusterIP, user can assign ip to it, or not, None means Headless Service
    # so if you are using Round-Robin service, don't include clusterIP field
    crud.ColumnValidator(field='clusterIP',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:O'],
                         nullable=True),
    # empty as RoundRobin or ClientIP
    crud.ColumnValidator(field='sessionAffinity',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='tags',
                         rule=validator.IterableValidator(crud.ColumnValidator.get_clean_data, tag_item_rules, 'check'),
                         validate_on=['check:O'],
                         converter=validator.StringToList(),
                         nullable=True),
    crud.ColumnValidator(field='selectors',
                         rule=validator.IterableValidator(crud.ColumnValidator.get_clean_data,
                                                          tag_item_rules,
                                                          'check',
                                                          length_min=1),
                         validate_on=['check:M'],
                         converter=validator.StringToList(),
                         nullable=True),
    crud.ColumnValidator(field='instances', rule=validator.TypeValidator(list), validate_on=['check:M'],
                         nullable=False),
]

service_instances_rules = [
    crud.ColumnValidator(field='name', rule=validator.LengthValidator(0, 255), validate_on=['check:O'], nullable=True),
    # TCP/UDP, default TCP
    crud.ColumnValidator(field='protocol',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='port', rule=validator.RegexValidator(r'^\d+$'), validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='targetPort',
                         rule=validator.RegexValidator(r'^\d+$'),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='nodePort',
                         rule=validator.RegexValidator(r'^\d*$'),
                         validate_on=['check:O'],
                         nullable=True),
]

destroy_rules = [
    crud.ColumnValidator(field='cluster',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='name', rule=validator.LengthValidator(1, 255), validate_on=['check:M'], nullable=False),
    # default 'default'
    crud.ColumnValidator(field='namespace',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
]

node_label_rules = [
    crud.ColumnValidator(field='cluster',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='tagName',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='tagValue',
                         rule=validator.TypeValidator(str),
                         validate_on=['check:M'],
                         nullable=False),
]

node_remove_label_rules = [
    crud.ColumnValidator(field='cluster',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='tagName',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='nodeName',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:O'],
                         nullable=True),
]

# 跨集群互联验证规则
interconnect_external_service_rules = [
    crud.ColumnValidator(field='local_cluster',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='service_name',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='local_namespace',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='remote_cluster',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='remote_namespace',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='remote_service_name',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='service_type',
                         rule=validator.InValidator(['ExternalName', 'Endpoint']),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='external_name',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='endpoints',
                         rule=validator.TypeValidator(list),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='ports',
                         rule=validator.TypeValidator(list),
                         validate_on=['check:O'],
                         nullable=True),
]

interconnect_network_policy_rules = [
    crud.ColumnValidator(field='cluster',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='policy_name',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='namespace',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='pod_selector',
                         rule=validator.TypeValidator(dict),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='allowed_clusters',
                         rule=validator.TypeValidator(list),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='allowed_ports',
                         rule=validator.TypeValidator(list),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='direction',
                         rule=validator.InValidator(['egress', 'ingress']),
                         validate_on=['check:O'],
                         nullable=True),
]

interconnect_setup_rules = [
    crud.ColumnValidator(field='local_cluster',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='remote_cluster',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='service_name',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='local_namespace',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='remote_namespace',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='service_type',
                         rule=validator.InValidator(['ExternalName', 'Endpoint']),
                         validate_on=['check:O'],
                         nullable=True),
    crud.ColumnValidator(field='enable_network_policy',
                         validate_on=['check:O'],
                         nullable=True,
                         converter=converter.BooleanConverter()),
]

# 共享 PVC 规则（支持多 Pod 共用一个 PVC，accessMode 通常为 ReadWriteMany）
shared_pvc_rules = [
    crud.ColumnValidator(field='cluster',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='correlation_id',
                         rule=validator.LengthValidator(1, 64),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='name',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    # default 'default'
    crud.ColumnValidator(field='namespace',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
    # 容量，单位 G，纯数字（整数或小数），如 "10" 或 "0.5"
    crud.ColumnValidator(field='capacity',
                         rule=validator.RegexValidator(r'^\d+(\.\d+)?$'),
                         validate_on=['check:M'],
                         nullable=False),
    # 共享 PVC 的核心：accessMode 决定多 Pod 共享能力
    # ReadWriteMany  — 多节点多 Pod 同时读写（共享 PVC 首选）
    # ReadOnlyMany   — 多节点多 Pod 只读
    # ReadWriteOnce  — 单节点读写（兼容普通场景）
    crud.ColumnValidator(field='accessMode',
                         rule=validator.InValidator(['ReadWriteMany', 'ReadWriteOnce', 'ReadOnlyMany']),
                         validate_on=['check:M'],
                         nullable=False),
    # StorageClass 名称，需为集群中已存在且支持所选 accessMode 的 StorageClass
    crud.ColumnValidator(field='storageClass',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    # 可选，作为 PVC 的额外标签写入，便于关联 CMDB 实例
    crud.ColumnValidator(field='instanceId',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
]

shared_pvc_destroy_rules = [
    crud.ColumnValidator(field='cluster',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    crud.ColumnValidator(field='name',
                         rule=validator.LengthValidator(1, 255),
                         validate_on=['check:M'],
                         nullable=False),
    # default 'default'
    crud.ColumnValidator(field='namespace',
                         rule=validator.LengthValidator(0, 255),
                         validate_on=['check:O'],
                         nullable=True),
]