apiVersion: v1
kind: Secret
metadata:
  name: wecube-secret
  namespace: demo-myapp
type: Opaque
data:
  # WeCube@1234
  mysql-password: V2VDdWJlQDEyMzQ=
  # Platform+Auth+Server+Secret
  signing-key: UGxhdGZvcm0rQXV0aCtTZXJ2ZXIrU2VjcmV0
  # Abcd1234
  auth-encrypt-seed: QWJjZDEyMzQ=
  # access_key
  s3-access-key: YWNjZXNzX2tleQ==
  # secret_key
  s3-secret-key: c2VjcmV0X2tleQ==
  # defaultEncryptSeed
  core-encrypt-seed: ZGVmYXVsdEVuY3J5cHRTZWVk
